# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.resize(1327, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 490, 150, 90))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 700 16pt \"Segoe UI\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 490, 150, 90))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 490, 150, 90))
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 0);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 490, 150, 90))
        self.pushButton_4.setStyleSheet("background-color:rgb(0, 85, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(600, 490, 150, 90))
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(750, 490, 150, 90))
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(900, 490, 150, 90))
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1050, 490, 150, 90))
        self.pushButton_8.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(750, 0, 150, 40))
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(600, 0, 150, 40))
        self.pushButton_10.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(900, 0, 150, 40))
        self.pushButton_11.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 0, 150, 40))
        self.pushButton_12.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(450, 0, 150, 40))
        self.pushButton_13.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(150, 0, 150, 40))
        self.pushButton_14.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(1050, 0, 150, 40))
        self.pushButton_15.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 0, 150, 40))
        self.pushButton_16.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(1200, 490, 150, 90))
        self.pushButton_17.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 700 16pt \"Segoe UI\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1200, 0, 150, 40))
        self.pushButton_18.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(150, 450, 150, 40))
        self.pushButton_19.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(1200, 450, 150, 40))
        self.pushButton_20.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(750, 450, 150, 40))
        self.pushButton_21.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(300, 450, 150, 40))
        self.pushButton_22.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(450, 450, 150, 40))
        self.pushButton_23.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(1050, 450, 150, 40))
        self.pushButton_24.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(900, 450, 150, 40))
        self.pushButton_25.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 450, 150, 40))
        self.pushButton_26.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(600, 450, 150, 40))
        self.pushButton_27.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_27.setObjectName("pushButton_27")
        MainWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 22))
        self.menubar.setObjectName("menubar")
        MainWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow1)
        self.statusbar.setObjectName("statusbar")
        MainWindow1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow1", "START"))
        self.pushButton_2.setText(_translate("MainWindow1", "STOP"))
        self.pushButton_3.setText(_translate("MainWindow1", "RESET"))
        self.pushButton_4.setText(_translate("MainWindow1", "HOME"))
        self.pushButton_5.setToolTip(_translate("MainWindow1", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:25px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; font-family:\'Courier New\'; background-color:#3a4055;\"><br/></pre></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow1", "SETUP"))
        self.pushButton_6.setText(_translate("MainWindow1", "MANUAL"))
        self.pushButton_7.setText(_translate("MainWindow1", "SERVO"))
        self.pushButton_8.setText(_translate("MainWindow1", "I/O LIST"))
        self.pushButton_9.setText(_translate("MainWindow1", "STATION_5"))
        self.pushButton_10.setText(_translate("MainWindow1", "STATION_4"))
        self.pushButton_11.setText(_translate("MainWindow1", "STATION_6"))
        self.pushButton_12.setText(_translate("MainWindow1", "STATION_2"))
        self.pushButton_13.setText(_translate("MainWindow1", "STATION_3"))
        self.pushButton_14.setText(_translate("MainWindow1", "STATION_1"))
        self.pushButton_15.setText(_translate("MainWindow1", "STATION_7"))
        self.pushButton_16.setText(_translate("MainWindow1", "MAIN"))
        self.pushButton_17.setText(_translate("MainWindow1", "INFO"))
        self.pushButton_18.setText(_translate("MainWindow1", "STATION_8"))
        self.pushButton_19.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_20.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_21.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_22.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_23.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_24.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_25.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_26.setText(_translate("MainWindow1", "SPARE"))
        self.pushButton_27.setText(_translate("MainWindow1", "SPARE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow1 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())
